In [1]:
!pip install numpy

In [1]:
#importing numpy
import numpy as np

In [5]:
#creating numpy
a = np.array([1,2,3])  #1D
b = np.array([(8.2,2,3),(7,8,9)],dtype = float)
c = np.array([[(8.2,2,3),(7,8,9)],[(3,2,1),(7,8,9)]],dtype = float)
print(a)
print(b)
print(c)


[1 2 3]
[[8.2 2.  3. ]
 [7.  8.  9. ]]
[[[8.2 2.  3. ]
  [7.  8.  9. ]]

 [[3.  2.  1. ]
  [7.  8.  9. ]]]


In [7]:
#intial placeholders 
#create an array of zeros
np.zeros([6])   #creating 1D array


array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros([2,4])  #creatig 2D array 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.zeros([2,3,4,])  #shape, rows,columns

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
#create an array of evenly spaced value 
d = np.arange(1,80,9) #step n-1(9-1=8)
print(d)

[ 1 10 19 28 37 46 55 64 73]


In [37]:
#create a array of spaced value (number of samples)
np.linspace(5,10,15)


array([ 5.        ,  5.35714286,  5.71428571,  6.07142857,  6.42857143,
        6.78571429,  7.14285714,  7.5       ,  7.85714286,  8.21428571,
        8.57142857,  8.92857143,  9.28571429,  9.64285714, 10.        ])

In [39]:
#create a constant array 
#create 1D array
e = np.full([15],30)  #columns
print(e)
print(e.ndim)    # to find no of dimmension

[30 30 30 30 30 30 30 30 30 30 30 30 30 30 30]
1


In [41]:
#create 2D array 
e = np.full([6,4,2],12)
print(e)
print(e.ndim)


[[[12 12]
  [12 12]
  [12 12]
  [12 12]]

 [[12 12]
  [12 12]
  [12 12]
  [12 12]]

 [[12 12]
  [12 12]
  [12 12]
  [12 12]]

 [[12 12]
  [12 12]
  [12 12]
  [12 12]]

 [[12 12]
  [12 12]
  [12 12]
  [12 12]]

 [[12 12]
  [12 12]
  [12 12]
  [12 12]]]
3


In [43]:
# create a 2*2 identity matrix 
f = np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [67]:
# create an array with random values 
np.random.random((2,4)) #rows,columns

array([[0.05899633, 0.54316668, 0.73030227, 0.16923253],
       [0.28058639, 0.11581543, 0.83193505, 0.18021308]])

In [88]:
# to find shape of an array 
arr = np.array([[2,4,6,8],
                [4,6,8,10],
                [6,8,10,12],
                [8,10,6,12]])
print(arr.shape)

(4, 4)


In [92]:
# to find number of elemwnts in array 
arr = np.array([[1,3,5],
                [3,5,7],
                [5,7,9]])
print(arr.size)

9


In [97]:
# to find len of array 
arr = np.array([[0,1,2,3],
                [1,2,3,4],
                [2,3,4,5],
                [3,4,5,6],
                [4,5,6,7]])
len(arr)

5

In [ ]:
#Access Array Elements:-

In [118]:
#you can access an array element by refering to its index number
#the index in numpy arrays start with 0
#meaning that the first element has index 0


In [176]:
arr = np.array([1,2,3,4])
print(arr[3])

4


In [178]:
import numpy as np
#adding two index position
arr = np.array([1,2,3,4,5])
print(arr[2] + arr[0] - arr[1])

2


In [255]:
#access 2D arrays
#access the element can the first row,second column
arr = np.array([[1,2,3,4,5],
               [6,7,8,9,10],
               [6,7,8,9,10],
               [6,7,8,9,1]])
print('2nd element on 1st row:',arr[3,4])

2nd element on 1st row: 1


In [262]:
#access 3D arrays
arr = np.array([[[1,2,3],[4,5,6]],
                [[1,22,3],[24,5,6]],
                [[1,32,32],[4,2,6]],
                [[7,8,9],[10,11,12]]])
#access by index
print([1,0,1]) #([2D,1D,element])

[1, 0, 1]


In [269]:
# Arithmetic operation on 2D Arrays :-

In [279]:
import numpy as np 
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
print(a)
print(b)

[[6 8 9]
 [5 7 3]]
[[2 1 6]
 [3 5 9]]


In [281]:
#addition
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a+b
print(c)

[[ 8  9 15]
 [ 8 12 12]]


In [284]:
#subraction
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a-b
print(c)

[[ 4  7  3]
 [ 2  2 -6]]


In [286]:
#multiplaction
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a*b
print(c)

[[12  8 54]
 [15 35 27]]


In [289]:
#division
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a/b
print(c)

[[3.         8.         1.5       ]
 [1.66666667 1.4        0.33333333]]


In [291]:
#modulus
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a%b
print(c)

[[0 0 3]
 [2 2 3]]


In [293]:
#float division 
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a//b
print(c)

[[3 8 1]
 [1 1 0]]


In [324]:
#exponentiation
a = np.array([[6,8,9],[5,7,3]])
b = np.array([[2,1,6],[3,5,9]])
c = a**b
print(c)

[[    36      8 531441]
 [   125  16807  19683]]


In [ ]:
#Arithmetic operations 3D arrays:-

In [305]:
import numpy as np 
#creating two 3D arrays
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
print(a)
print(b)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
[[[12 11 10]
  [ 9  8  7]
  [ 6  5  4]
  [ 3  2  1]]]


In [308]:
#addition 
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a+b
print(c)

[[[13 13 13]
  [13 13 13]
  [13 13 13]
  [13 13 13]]]


In [310]:
#subraction
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a-b
print(c)

[[[-11  -9  -7]
  [ -5  -3  -1]
  [  1   3   5]
  [  7   9  11]]]


In [313]:
#multiplication
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a*b
print(c)

[[[12 22 30]
  [36 40 42]
  [42 40 36]
  [30 22 12]]]


In [316]:
#division
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a/b
print(c)


[[[ 0.08333333  0.18181818  0.3       ]
  [ 0.44444444  0.625       0.85714286]
  [ 1.16666667  1.6         2.25      ]
  [ 3.33333333  5.5        12.        ]]]


In [318]:
#modulus
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a%b
print(c)


[[[1 2 3]
  [4 5 6]
  [1 3 1]
  [1 1 0]]]


In [320]:
#float division
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a//b
print(c)


[[[ 0  0  0]
  [ 0  0  0]
  [ 1  1  2]
  [ 3  5 12]]]


In [322]:
#exponentiation
a = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
b = np.array([[[12,11,10],[9,8,7],[6,5,4],[3,2,1]]])
c = a**b
print(c)

[[[     1   2048  59049]
  [262144 390625 279936]
  [117649  32768   6561]
  [  1000    121     12]]]
